from wavNN.data_generators.cifar_generator import CIFARGenerator
from wavNN.data_generators.mnist_generator import MNISTGenerator
from wavNN.data_generators.fashion_mnist_generator import FashionMNISTGenerator
