from WavPool.data_generators.cifar_generator import CIFARGenerator
from WavPool.data_generators.mnist_generator import MNISTGenerator
from WavPool.data_generators.fashion_mnist_generator import FashionMNISTGenerator
